[tool.poetry]
name = "experiment"
version = "0.1.0"
description = "汎用環境"
authors = ["Author1"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.9"
torch = { url = "https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp310-cp310-win_amd64.whl"}
torchvision = { url = "https://download.pytorch.org/whl/cu116/torchvision-0.14.1%2Bcu116-cp310-cp310-win_amd64.whl"}
torchaudio = { url = "https://download.pytorch.org/whl/cu116/torchaudio-0.13.1%2Bcu116-cp310-cp310-win_amd64.whl"}
opencv-python = "^4.7.0.68"
pandas = "^1.5.3"

[tool.poetry.group.dev.dependencies]
pyproject-flake8 = "^6.0.0"
mypy = "^1.0.0"
black = "^23.1.0"
isort = "^5.12.0"
ipykernel = "^6.21.1"

[build-system]
requires = ["poetry>=1.3.2"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 120
max-complexity = 10  # 循環的複雑度の最大値
ignore = "E203,E266,W503,W504,"
# E203: ":"の前の空白を入れないルール
# E266: コメントアウトのときに"#"を複数使わないようにするルール
# W503: 演算子の前に改行しないようにするルール

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
exclude = [
    "venv/*",
    '\.venv/*',
]

[tool.black]
target-version = ["py310"]
line-length = 120

[tool.isort]
line_length = 120
multi_line_output = 3
ensure_newline_before_comments = true
use_parentheses = true
